name: AZenith

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - ".github/scripts/**"
      - "manager/**"
      - "archdaemon/**"
      - "tweakfls/**"
      - "mainfiles/**"
      - "azenithApplist.json"
      - "version"
      - "version_type"

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build AZenith
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      
      - name: Verify Module
        run: bash .github/scripts/verify.sh
        
      - name: Copy changelog file
        run: bash .github/scripts/changelog.sh

      - name: Determine Build Type
        id: build_type
        run: |
          # Membaca isi file dan menghapus spasi/newline tersembunyi
          V_TYPE=$(cat version_type | tr -d '\n\r ')
          echo "V_TYPE=$V_TYPE" >> $GITHUB_ENV
          echo "Build mode set to: $V_TYPE"
  
      - name: NDK Setup
        uses: nttld/setup-ndk@v1.6.0
        with:
          ndk-version: r29

      - name: Compile Daemon
        working-directory: ./archdaemon
        run: |
          if [ "$V_TYPE" == "experimental" ]; then
            ndk-build NDK_DEBUG=1
          else
            ndk-build
          fi

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Compile AZenith Profilesettings
        working-directory: ./binprofiles
        run: |
          if [ "$V_TYPE" == "experimental" ]; then
            cargo ndk -t arm64-v8a build
          else
            cargo ndk -t arm64-v8a build --release
          fi

      - name: Compile AZenith Utility
        working-directory: ./binutils
        run: |
          if [ "$V_TYPE" == "experimental" ]; then
            cargo ndk -t arm64-v8a build
          else
            cargo ndk -t arm64-v8a build --release
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: temurin

      - name: Build Manager APK
        working-directory: ./manager
        run: |
          chmod +x ./gradlew
          if [ "$V_TYPE" == "experimental" ]; then
            ./gradlew clean assembleDebug
          else
            ./gradlew clean assembleRelease
          fi
        env:
          KS_PWD: ${{ secrets.KEYSTORE_PASSWORD }}
                    
      - name: Compile Flashable Zip
        id: compileZip
        run: bash .github/scripts/compile_zip.sh

      - name: Upload To Telegram
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TITLE: AZenith
        run: |
          if [ -n "$CHAT_ID" ] && [ -n "$BOT_TOKEN" ]; then
            export VERSION=$(git rev-list --count HEAD)
            bash .github/scripts/telebot.sh "${{ steps.compileZip.outputs.zipName }}"
          else
            echo "Telegram bot token or chatid is undefined!"
            echo 'Telegram secrets not set, skipping upload.'
          fi

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.compileZip.outputs.artifactName }}
          path: ${{ steps.compileZip.outputs.zipName }}
          if-no-files-found: error
